[package]
name = "cellular_automaton"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.3"
bevy = "0.13.2"
rand = "0.8"
rand_chacha = "0.3.1"
criterion = "0.3"
rustfft = "5.1"
rayon = "1.10"